spring:
  application:
    ###服务的名称
    name: meitemayikt-order
  cloud:
    nacos:
      discovery:
        ###nacos注册地址
        server-addr: 127.0.0.1:8848
server:
  port: 8090

##8080 8081 8082---会员相关 8090 8091 8092 订单相关